/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package att;

import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import javax.swing.JOptionPane;
import util.AdaptadorMySQL;
import util.Fecha;

/**
 *
 * @author Administrador
 */ 
public class CrearMarcacion extends javax.swing.JFrame {

    static HashMap agentes;
    static Object[] claves;
    static String[] MESES = {"ene", "feb", "mar", "abr", "may", "jun", "jul", "ago", "sep", "oct", "nov", "dic"};
    static Marcacion marcacion;

    public static String[] getNombres() {
        String[] nombres = {"Agente a", "Agente b"};

        try {

            nombres = new String[agentes.size()];

            //   System.out.println(agentes.keySet());
            for (int i = 0; i < nombres.length; i++) {

                nombres[i] = (String) agentes.get(claves[i]);
            }

        } catch (Exception e) {
            ArrayList<StackTraceElement> stea = new ArrayList<>();

            stea.addAll(Arrays.asList(e.getStackTrace()));

            System.out.println(stea);
        }
        return nombres;
    }

    /**
     * Creates new form CrearMarcacion
     */
    public CrearMarcacion() {
        initComponents();

        jCodigo.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"Entrada", "Salida"}));

        tDia.setText(Fecha.hoy().getDia() + "");
        tAnio.setText(Fecha.hoy().getAnio() + "");
        tMes.setText((Fecha.hoy().getMes()+1) + "");

        agentes = new Agente().nombres;
        claves = agentes.keySet().toArray();

        jList1.setModel(new javax.swing.AbstractListModel() {

            String[] strings = getNombres();

            public int getSize() {
                return strings.length;
            }

            public Object getElementAt(int i) {
                return strings[i];
            }
        });
        jList1.setSelectedIndex(0);
        jScrollPane1.setViewportView(jList1);

        lResultado.setForeground(Color.RED);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tReloj = new javax.swing.JTextField();
        tMes = new javax.swing.JTextField();
        tAnio = new javax.swing.JTextField();
        tDia = new javax.swing.JTextField();
        tHora = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        taConsulta = new javax.swing.JTextArea();
        jCodigo = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        bGuardar = new javax.swing.JButton();
        lResultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Crear Marcacion");
        setPreferredSize(new java.awt.Dimension(640, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Agente");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 12, -1, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Mes");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 33, -1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Año");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, 37, -1));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Dia");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 38, -1));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Hora");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 37, -1));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Tipo");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, -1, -1));

        tReloj.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tReloj.setText("1");
        tReloj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tRelojActionPerformed(evt);
            }
        });
        getContentPane().add(tReloj, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 80, 70, 22));

        tMes.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tMes.setText("3");
        getContentPane().add(tMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 30, 70, 22));

        tAnio.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tAnio.setText("2024");
        getContentPane().add(tAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, 70, 22));

        tDia.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tDia.setText("jTextField4");
        tDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tDiaActionPerformed(evt);
            }
        });
        getContentPane().add(tDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 70, 22));

        tHora.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tHora.setText("07:00:00");
        getContentPane().add(tHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 80, 70, 22));

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 12, 211, 360));

        jButton1.setText("Ver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 59, -1));

        taConsulta.setColumns(20);
        taConsulta.setLineWrap(true);
        taConsulta.setRows(5);
        jScrollPane2.setViewportView(taConsulta);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 190, 300, 180));

        jCodigo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 80, 70, 22));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Reloj");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, 37, -1));

        bGuardar.setText("Insertar");
        bGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(bGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, -1, -1));

        lResultado.setText("Resultado: ");
        getContentPane().add(lResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 138, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            String tarjeta = claves[jList1.getSelectedIndex()] + "";
            String agente = (String) jList1.getSelectedValue();
            String hora = tHora.getText();
            String reloj = tReloj.getText();

            int codigo = 0;

            if (reloj.equals("1")) {
                codigo += 20 + jCodigo.getSelectedIndex();
            } else {
                codigo += jCodigo.getSelectedIndex();
            }

            String tabla = "marcaciones_"+MESES[new Integer(tMes.getText())-1]+"_"+tAnio.getText();
            //String tabla = "marcaciones_dic_2019";
            System.out.println(tabla);

            marcacion = new Marcacion();

            marcacion.setTarjeta(tarjeta);
            marcacion.setAgente(agente);
            marcacion.setLegajo(tarjeta);
            marcacion.setFecha(new Fecha(tDia.getText(), (new Integer(tMes.getText())-1) +"", tAnio.getText()));
            //  marcacion.setFecha(new Fecha(13+"", 11+"", 2019+""));
      //      Fecha temp = marcacion.getFecha();

            //temp.setMes(temp.getMes()-1);
        //    temp.setMes(11);

     //       System.out.println(temp);
            
      //      System.err.println(temp);
    //        marcacion.setFecha(temp);

            marcacion.setHora(hora);
            marcacion.setFechaProceso(new Fecha());
            marcacion.setReloj(reloj);
            marcacion.setCodigo(codigo);
            marcacion.setTipo(2);

            marcacion.setId(marcacion.calcularId());

        //String tabla = "INSERT INTO " + "marcaciones_"+MESES[new Integer(tMes.getText())]+"_"+tAnio.getText() + " VALUES(";
            // consulta += tarjeta + ", "
            taConsulta.setText(marcacion.getConsultaInsert(tabla) + ";");
            // System.err.println(tabla);
        } catch (Exception e) {
            System.out.println(e);
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void tRelojActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tRelojActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tRelojActionPerformed

    private void bGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGuardarActionPerformed
        // TODO add your handling code here:
        AdaptadorMySQL datos = new AdaptadorMySQL();

        String consulta = taConsulta.getText();

        JOptionPane.showMessageDialog(this, marcacion);

        try {
            int count = datos.actualizar(consulta);

            taConsulta.setText("");

            lResultado.setText(count + " insertado(s)");

        } catch (SQLException e) {
            lResultado.setText("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_bGuardarActionPerformed

    private void tDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tDiaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearMarcacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearMarcacion().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bGuardar;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jCodigo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lResultado;
    private javax.swing.JTextField tAnio;
    private javax.swing.JTextField tDia;
    private javax.swing.JTextField tHora;
    private javax.swing.JTextField tMes;
    private javax.swing.JTextField tReloj;
    private javax.swing.JTextArea taConsulta;
    // End of variables declaration//GEN-END:variables
}
