/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package att;

import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatIntelliJLaf;
import com.formdev.flatlaf.FlatLightLaf;
import java.util.ArrayList;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.event.AncestorEvent;
import javax.swing.event.AncestorListener;
import javax.swing.table.DefaultTableCellRenderer;
import util.AdaptadorMySQL;

/**
 *
 * @author usuario
 */
public class ManejadorIrregularidades extends javax.swing.JFrame {

    static String idSeleccionada = "";
    static String consulta = "";
    static int indice = 0;

    /**
     * Creates new form ManejadorIrregularidades
     */
    public ManejadorIrregularidades() {
        initComponents();

        tbTablaIrregular.addAncestorListener(new AncestorListener() {

            @Override
            public void ancestorAdded(final AncestorEvent e) {
                final AncestorListener al = this;
                SwingUtilities.invokeLater(new Runnable() {

                    @Override
                    public void run() {
                        final JComponent component = e.getComponent();
                        component.requestFocusInWindow();
                        component.removeAncestorListener(al);
                    }
                });
            }

            @Override
            public void ancestorMoved(final AncestorEvent e) {
            }

            @Override
            public void ancestorRemoved(final AncestorEvent e
            ) {
            }
        });
    }

    public ManejadorIrregularidades(ArrayList<ArrayList<String>> irrs) throws Exception {

        System.err.println(Lector.getMarcacionesIndividuales_());

        Lector.crearConsultaIrregularidades(Lector.irregu);

        initComponents();

        String[][] contenido = new String[irrs.size()][];
        ArrayList<String> tempo = new ArrayList<>();

        for (int i = 0; i < contenido.length; i++) {
            contenido[i] = new String[7];
        }

        for (int i = 0; i < contenido.length; i++) {

            tempo = irrs.get(i);

            for (int j = 0; j < tempo.size(); j++) {
                contenido[i][j] = tempo.get(j);

            }

        }

        tbTablaIrregular.setModel(new javax.swing.table.DefaultTableModel(
                contenido,
                new String[]{
                    "Id", "Tarjeta", "Agente", "Fecha", "Hora",
                    "Codigo", "Tipo"
                }
        ) {

            @Override
            public boolean isCellEditable(int row, int column) {
                //all cells false
                return false;
            }
        });

        int[] anchos = {60, 15, 113, 36, 36, 20, 20};

        for (int i = 0; i < anchos.length; i++) {
            tbTablaIrregular.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
        }

        DefaultTableCellRenderer render = new DefaultTableCellRenderer();

        render.setHorizontalAlignment(javax.swing.JLabel.CENTER);

        tbTablaIrregular.getColumnModel().getColumn(1).setCellRenderer(render);
        tbTablaIrregular.getColumnModel().getColumn(3).setCellRenderer(render);
        
          try {
            UIManager.setLookAndFeel(new FlatIntelliJLaf());
        } catch (Exception e) {

        }
    }

    public void actualizar(ArrayList<ArrayList<String>> irrs) {
        String[][] contenido = new String[irrs.size()][];
        ArrayList<String> tempo;

        for (int i = 0; i < contenido.length; i++) {
            contenido[i] = new String[7];
        }

        for (int i = 0; i < contenido.length; i++) {

            tempo = irrs.get(i);

            for (int j = 0; j < tempo.size(); j++) {
                contenido[i][j] = tempo.get(j);

            }

        }

        tbTablaIrregular.setModel(new javax.swing.table.DefaultTableModel(
                contenido,
                new String[]{
                    "Id", "Tarjeta", "Agente", "Fecha", "Hora",
                    "Codigo", "Tipo"
                }
        ));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbTablaIrregular = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        tIdSeleccionado = new javax.swing.JTextField();
        bAnular = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        tHora = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        bCambiarCodigo = new javax.swing.JButton();
        bCrearSalida = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        taConsulta = new javax.swing.JTextArea();
        jButton7 = new javax.swing.JButton();
        tFecha = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        tOperacion = new javax.swing.JTextField();
        bActualizar = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Manejador Irr 1.0");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Manejar Irregularidades");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 13, -1, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbTablaIrregular.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbTablaIrregular.setPreferredSize(null);
        tbTablaIrregular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbTablaIrregularMouseClicked(evt);
            }
        });
        tbTablaIrregular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbTablaIrregularKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbTablaIrregular);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 13, 800, 275));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 36, 820, -1));

        jLabel2.setText("Seleccionado");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 90, -1));

        tIdSeleccionado.setText(" ");
        tIdSeleccionado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tIdSeleccionadoActionPerformed(evt);
            }
        });
        getContentPane().add(tIdSeleccionado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 154, -1));

        bAnular.setText("Anular");
        bAnular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAnularActionPerformed(evt);
            }
        });
        getContentPane().add(bAnular, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 111, -1));

        jButton2.setText("Cambiar Hora");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, -1, -1));

        tHora.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tHora.setText(" ");
        getContentPane().add(tHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, 110, -1));

        jButton3.setText("Cambiar Fecha");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, 111, -1));

        jTextField3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField3.setText("23:59:00");
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 350, 100, -1));

        bCambiarCodigo.setText("Cambiar Codigo");
        bCambiarCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCambiarCodigoActionPerformed(evt);
            }
        });
        getContentPane().add(bCambiarCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 111, -1));

        bCrearSalida.setText("Salida");
        bCrearSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCrearSalidaActionPerformed(evt);
            }
        });
        getContentPane().add(bCrearSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 350, 100, -1));

        jButton6.setText("Entrada");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 380, 100, -1));

        jLabel3.setText("Consulta Generada");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 414, -1, -1));

        taConsulta.setColumns(20);
        taConsulta.setLineWrap(true);
        taConsulta.setRows(5);
        taConsulta.setWrapStyleWord(true);
        jScrollPane3.setViewportView(taConsulta);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 430, 570, -1));

        jButton7.setText("Ejecutar >>>");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 550, 120, 30));

        tFecha.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tFecha.setText("  ");
        getContentPane().add(tFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 380, 110, -1));

        jTextField5.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField5.setText("00:00:00");
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 380, 100, -1));

        tOperacion.setText("...");
        getContentPane().add(tOperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 443, 143, -1));

        bActualizar.setText("Actualizar");
        bActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(bActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 483, 143, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbTablaIrregularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbTablaIrregularMouseClicked
        // TODO add your handling code here:
        String id = tbTablaIrregular.getValueAt(tbTablaIrregular.getSelectedRow(), 0).toString();

        idSeleccionada = id;

        tIdSeleccionado.setText(idSeleccionada);

        tFecha.setText(tbTablaIrregular.getValueAt(tbTablaIrregular.getSelectedRow(), 3).toString());
        tHora.setText(tbTablaIrregular.getValueAt(tbTablaIrregular.getSelectedRow(), 4).toString());
    }//GEN-LAST:event_tbTablaIrregularMouseClicked

    private void bAnularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAnularActionPerformed
        // TODO add your handling code here:
        anular();

    }//GEN-LAST:event_bAnularActionPerformed

    public void anular() {
        consulta = "update " + Lector.TABLA_MARCACIONES + " set tipo = 4 \n"
                + " where id = '" + idSeleccionada + "';";

        taConsulta.setText(consulta);
        ejecutar("Anulado!!!");
    }

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void tIdSeleccionadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tIdSeleccionadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tIdSeleccionadoActionPerformed

    private void bCambiarCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCambiarCodigoActionPerformed
        // TODO add your handling code here:

        int codigo = new Integer(tabla(5));
        int propuesto = 21;

        if (codigo == 21) {
            propuesto = 20;
        }

        consulta = "update " + Lector.TABLA_MARCACIONES + " set codigo = " + propuesto + " \n"
                + " where id = '" + idSeleccionada + "';";

        taConsulta.setText(consulta);

        ejecutar("Codigo cambiado");
    }//GEN-LAST:event_bCambiarCodigoActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:

        ejecutar("Realizado!!!");


    }//GEN-LAST:event_jButton7ActionPerformed

    private void bCrearSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCrearSalidaActionPerformed
        // TODO add your handling code here:

        int filaSeleccionada = tbTablaIrregular.getSelectedRow();

        String consulta = "INSERT INTO ";

        int randInt = (int) (Math.random() * 100);
        int reloj = 1;
        // String legajo = "";
        String fecha_proceso = "";

        try {
            AdaptadorMySQL datos = new AdaptadorMySQL();

            datos.consultar("select reloj, legajo, fecha_proceso from " + Lector.TABLA_MARCACIONES
                    + " where " + tIdSeleccionado.getText());

            datos.resultados.next();

            reloj = datos.resultados.getInt(1);
            //  legajo = datos.resultados.getString("legajo");
            fecha_proceso = datos.resultados.getString(3);

        } catch (Exception e) {

        }

        consulta += Lector.TABLA_MARCACIONES + " values ('";
        consulta += tIdSeleccionado.getText() + randInt + "', '";
        consulta += tbTablaIrregular.getValueAt(filaSeleccionada, 1) + "', '";
        consulta += tbTablaIrregular.getValueAt(filaSeleccionada, 2) + "', '";
        consulta += tbTablaIrregular.getValueAt(filaSeleccionada, 1) + "', '";
        consulta += tbTablaIrregular.getValueAt(filaSeleccionada, 3) + "', '";
        consulta += "23:59:00" + "', '";
        consulta += reloj + "', '";
        consulta += "21" + "', '";
        consulta += fecha_proceso + "', '";
        consulta += "2" + "');";

        taConsulta.setText(consulta);

        ejecutar("Salida Ingresada");
        //  tbTablaIrregular.set
    }//GEN-LAST:event_bCrearSalidaActionPerformed


    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:

        int filaSeleccionada = tbTablaIrregular.getSelectedRow();

        String consulta = "INSERT INTO ";

        int randInt = (int) (Math.random() * 100);
        int reloj = 1;
        // String legajo = "";
        String fecha_proceso = "";

        try {
            AdaptadorMySQL datos = new AdaptadorMySQL();

            datos.consultar("select reloj, legajo, fecha_proceso from " + Lector.TABLA_MARCACIONES
                    + " where " + tIdSeleccionado.getText());

            datos.resultados.next();

            reloj = datos.resultados.getInt(1);
            //  legajo = datos.resultados.getString("legajo");
            fecha_proceso = datos.resultados.getString(3);

        } catch (Exception e) {

        }

        consulta += Lector.TABLA_MARCACIONES + " values ('";
        consulta += tIdSeleccionado.getText() + randInt + "', '";
        consulta += tbTablaIrregular.getValueAt(filaSeleccionada, 1) + "', '";
        consulta += tbTablaIrregular.getValueAt(filaSeleccionada, 2) + "', '";
        consulta += tbTablaIrregular.getValueAt(filaSeleccionada, 1) + "', '";
        consulta += tbTablaIrregular.getValueAt(filaSeleccionada, 3) + "', '";
        consulta += "00:00:00" + "', '";
        consulta += reloj + "', '";
        consulta += "20" + "', '";
        consulta += fecha_proceso + "', '";
        consulta += "2" + "');";

        taConsulta.setText(consulta);

        ejecutar("Entrada Ingresada");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void bActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActualizarActionPerformed
        // TODO add your handling code here:

        System.out.println("Actualizar");

        try {
            Lector.getMarcacionesIndividuales_();

            String[][] contenido = new String[Lector.irregu.size()][];
            ArrayList<String> tempo = new ArrayList<>();

            AdaptadorMySQL datos;

            String consultaI = Lector.crearConsultaIrregularidades(Lector.irregu);

            System.err.println("Consulta Irregularidades");
            System.out.println(consultaI);
            // System.exit(0);

            ArrayList<ArrayList<String>> arrayMI = new ArrayList<>();
            //ArrayList<String> tempo;

            datos = new AdaptadorMySQL();

            datos.consultar(consultaI);

            while (datos.resultados.next()) {
                tempo = new ArrayList<>();

                for (int i = 0; i < 7; i++) {
                    tempo.add(datos.resultados.getString(i + 1));

                }
                arrayMI.add(tempo);
            }

            for (int i = 0; i < contenido.length; i++) {
                contenido[i] = new String[7];
            }

            for (int i = 0; i < contenido.length; i++) {

                for (int j = 0; j < 7; j++) {
                    //tempo[j] = Lector.irregu.get(i);

                }

                for (int j = 0; j < tempo.size(); j++) {
                    contenido[i][j] = tempo.get(j);

                }

            }
        } catch (Exception e) {
        }
        /*  tbTablaIrregular.setModel(new javax.swing.table.DefaultTableModel(
                contenido,
                new String[]{
                    "Id", "Tarjeta", "Agente", "Fecha", "Hora",
                    "Codigo", "Tipo"
                }
        ));*/
    }//GEN-LAST:event_bActualizarActionPerformed

    private void tbTablaIrregularKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbTablaIrregularKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyChar() == 'a') {
            anular();
        }
    }//GEN-LAST:event_tbTablaIrregularKeyPressed

    void ejecutar(String mensaje) {
        AdaptadorMySQL datos = new AdaptadorMySQL();

        consulta = taConsulta.getText();

        try {
            datos.actualizar(consulta);
            //datos.cerrar();
            //JOptionPane.showMessageDialog(null, "Exito");
            tOperacion.setText(mensaje);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    String tabla(int fila, int columna) {
        return tbTablaIrregular.getValueAt(fila, columna).toString();
    }

    String tabla(int columna) {
        return tbTablaIrregular.getValueAt(tbTablaIrregular.getSelectedRow(), columna).toString();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
  
        try {
            UIManager.setLookAndFeel(new FlatIntelliJLaf());
        } catch (Exception e) {

        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManejadorIrregularidades().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bActualizar;
    private javax.swing.JButton bAnular;
    private javax.swing.JButton bCambiarCodigo;
    private javax.swing.JButton bCrearSalida;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField tFecha;
    private javax.swing.JTextField tHora;
    private javax.swing.JTextField tIdSeleccionado;
    private javax.swing.JTextField tOperacion;
    private javax.swing.JTextArea taConsulta;
    private javax.swing.JTable tbTablaIrregular;
    // End of variables declaration//GEN-END:variables
}

class RequestFocusListener implements AncestorListener {

    @Override
    public void ancestorAdded(final AncestorEvent e) {
        final AncestorListener al = this;
        SwingUtilities.invokeLater(new Runnable() {

            @Override
            public void run() {
                final JComponent component = e.getComponent();
                component.requestFocusInWindow();
                component.removeAncestorListener(al);
            }
        });
    }

    @Override
    public void ancestorMoved(final AncestorEvent e) {
    }

    @Override
    public void ancestorRemoved(final AncestorEvent e) {
    }

}
