/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package att;

import util.AdaptadorMySQL;

/**
 *
 * @author SistemasRC0011
 */
public class VerConsultas extends javax.swing.JFrame {
    
    String tablaDetalle = "";
    String tablaHoras = "";

    /**
     * Creates new form VerConsultas
     */
    public VerConsultas() {
        initComponents();
    }

    public VerConsultas(String tablaDetalle, String consultasDetalle, String tablaHoras, String consultasHoras) {
        initComponents();

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        this.tablaDetalle = tablaDetalle;
        this.tablaHoras = tablaHoras;

        tConsultasDetalle.setFont(new java.awt.Font("Consolas", 0, 13)); // NOI18N
        tConsultasHoras.setFont(new java.awt.Font("Consolas", 0, 13));

        tConsultasDetalle.setText(consultasDetalle);
        tConsultasHoras.setText(consultasHoras);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tConsultasDetalle = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tConsultasHoras = new javax.swing.JTextArea();
        bActualizarHoras = new javax.swing.JButton();
        bActualizarDetalles = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(null);
        setPreferredSize(new java.awt.Dimension(716, 520));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tConsultasDetalle.setColumns(20);
        tConsultasDetalle.setFont(new java.awt.Font("Monospaced", 3, 18)); // NOI18N
        tConsultasDetalle.setRows(5);
        jScrollPane1.setViewportView(tConsultasDetalle);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 610, 180));

        tConsultasHoras.setColumns(20);
        tConsultasHoras.setRows(5);
        jScrollPane2.setViewportView(tConsultasHoras);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 610, 166));

        bActualizarHoras.setText("Actualizar Horas");
        bActualizarHoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActualizarHorasActionPerformed(evt);
            }
        });
        getContentPane().add(bActualizarHoras, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 450, 160, -1));

        bActualizarDetalles.setText("Actualizar Detalles");
        bActualizarDetalles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActualizarDetallesActionPerformed(evt);
            }
        });
        getContentPane().add(bActualizarDetalles, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, 150, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bActualizarDetallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActualizarDetallesActionPerformed
        // TODO add your handling code here:
        
        AdaptadorMySQL datos = new AdaptadorMySQL();
        
        String query_truncate = "TRUNCATE TABLE " + tablaDetalle + ";";
        String query_insert = tConsultasDetalle.getText();
        
        try{
            datos.actualizar(query_truncate);
        }catch(Exception e){
            System.err.println(e);
        }
        try{
            datos.actualizar(query_insert);
        }catch(Exception e){
            System.err.println(e);
        }

    }//GEN-LAST:event_bActualizarDetallesActionPerformed

    private void bActualizarHorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActualizarHorasActionPerformed
        // TODO add your handling code here:
        AdaptadorMySQL datos = new AdaptadorMySQL();
        
        String query_truncate = "TRUNCATE TABLE " + tablaHoras + ";";
        String query_insert = tConsultasHoras.getText();
        
        try{
            datos.actualizar(query_truncate);
        }catch(Exception e){
            System.err.println(e);  
        }
        try{
            datos.actualizar(query_insert);
        }catch(Exception e){
            System.err.println(e);
        }
    }//GEN-LAST:event_bActualizarHorasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerConsultas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bActualizarDetalles;
    private javax.swing.JButton bActualizarHoras;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea tConsultasDetalle;
    private javax.swing.JTextArea tConsultasHoras;
    // End of variables declaration//GEN-END:variables
}
